services:
  app:
    build: .
    container_name: oktapux-share
    ports:
      - "3003:3000"
    volumes:
      - ./uploads:/app/uploads
      - oktapux_db:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  oktapux_db:
