services:
  app:
    build: .
    container_name: oktapux-share
    ports:
      - "3003:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - ENCRYPTION_KEY_SECRET=${ENCRYPTION_KEY_SECRET}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
    restart: unless-stopped
