name: Cleanup Registry
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  delete-images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete packages older than 7 days (keep at least 5)
        uses: davahome/ghcr-cleanup@v1.1
        with:
          token: ${{ secrets.GHCR_PAT }}
          package: oktapux-share
          owner: users/kannomer
          minimum_days: 7
          keep_versions: 5
          delete_tagged: true
          delete_untagged: true
